/** Light property-app design tokens (Rightmove / Zoopla style) */
export const theme = {
  colors: {
    background: "#FFFFFF",
    card: "#F8FAFC",
    white: "#FFFFFF",
    navy: "#0F172A",
    navyDark: "#0F172A",
    text: "#0F172A",
    textSecondary: "#475569",
    textMuted: "#64748B",
    textLight: "#94A3B8",
    border: "#E2E8F0",
    borderLight: "#F1F5F9",
    primary: "#1B4FD8",
    primaryDark: "#1640B8",
    green: "#16A34A",
    greenLight: "#DCFCE7",
    greenText: "#15803D",
    red: "#DC2626",
    redLight: "#FEE2E2",
    redText: "#B91C1C",
    amber: "#D97706",
    blueLight: "#EFF6FF",
    grayBadge: "#F1F5F9",
    grayBadgeText: "#475569",
  },
  radius: {
    lg: 10,
    xl: 12,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  shadow: {
    card: {
      shadowColor: "#0F172A",
      shadowOpacity: 0.04,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    button: {
      shadowColor: "#1B4FD8",
      shadowOpacity: 0.18,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 3 },
      elevation: 2,
    },
  },
} as const;
